### ISSUE TITLE
Markdown mode - `:\` renders as `:\\`

### ISSUE THREAD

**Issue by AGBrown** [Neftas/supplementary-buttons-anki#64]
Entering 

<pre>`:\`</pre>

or a code block with `:\` in it renders as

<pre>:\\</pre>

Switching out of markdown mode replaces the original markdown with

<pre>`:\\`</pre>

Amusingly switching in and out of markdown mode then causes the `\`s to multiply like rabbits.

**Comment by Neftas** [comment]
This is probably a problem in the `html2text` plugin. I will look into it.

**Comment by trehehaeuser** [comment]
Hi Stefan,

that are too many emails for me. Can you delete me from the email-list?

Best,

Tom

**Comment by Neftas** [comment]
Hi Tom, there is not such thing as a email list. I think you can get rid of the emails by unwatching this repo.

**Comment by Neftas** [comment]
This is fixed in bdcb8ba.

**Comment by AGBrown** [comment]
Is this now in 0c835aa9, and is that the same version that was released to https://ankiweb.net/shared/info/162313389 on 26/01/2016? 

If so then I am

1. still seeing the problem in the first part of the original issue - if you enter \`:\\\` (<kbd>\`</kbd> <kbd>:</kbd> <kbd>\\</kbd> <kbd>\`</kbd>) and then trigger markdown mode
1. no longer seeing an issue in the second part: enter a code block (triple-backtick delimited block of code) containing `:\` (<kbd>:</kbd> <kbd>\\</kbd>) and then trigger markdown mode.

**Comment by AGBrown** [comment]
Ok, I'm thinking maybe something didn't work when i reinstalled it from AnkiWeb, because I'm also continuing to see #65 happen as well as the inline-code issue in my last comment. I'll wait for you to confirm if 0c835aa is indeed the version on ankiweb, and contains these fixes, before reporting any more.

**Comment by Neftas** [comment]
See the comment on the other issue: I have not yet uploaded a new version to AnkiWeb. I will tomorrow.

**Comment by AGBrown** [comment]
@Neftas - my bad, sorry for the spam. Feel free to delete all the comments I wrote as they're just causing noise on the issues.

**Comment by Neftas** [comment]
No worries, I am thankful that you are taking the time to make detailed bug reports and provide me with useful feedback.

**Comment by Neftas** [comment]
I've just posted the fixes on AnkiWeb.

**Comment by AGBrown** [comment]
@Neftas Both those test cases now work as expected.
